services:
  php:
    container_name: php-fpm
    build:
      context: ./docker/php/
      dockerfile: ./Dockerfile
    volumes:
      - ./app/backend:/var/www/html
    working_dir: /var/www/html
    networks:
      - cyber

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./app/backend:/var/www/html
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - php
    networks:
      - cyber

  vue:
    container_name: vue
    build:
      context: ./
      dockerfile: ./docker/vue/Dockerfile
    volumes:
      - ./app/frontend:/app
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    networks:
      - cyber

networks:
  cyber:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
  mysql_data: